### ISSUE TITLE
Follow-up from "Intel compiler 2021.3.0 fixes"

### ISSUE THREAD

**Issue by matt-frey** [IPPL-framework/ippl#116]
In GitLab by @srikrrish on Jul 4, 2022, 11:50

The following discussion from !125 should be addressed:

- [ ] @matt-frey started a [discussion](https://gitlab.psi.ch/OPAL/Libraries/ippl/-/merge_requests/125#note_38971):  (+2 comments)

    > We need to find a solution for this.

**Comment by srikrrish** [comment]
This is fixed.
