### ISSUE TITLE
Implement different interpolation strategies

### ISSUE THREAD

**Issue by matt-frey** [IPPL-framework/ippl#158]
In GitLab by @vinciguerra_a on May 2, 2023, 17:11

The scatter/gather implementations in !157 introduce helper functions in `ParticleAttrib.h` for the interpolation. To support higher or lower order interpolation, these should be moved to a new file and a struct should be introduced for the different kinds of interpolation.

**Comment by srikrrish** [comment]
These are now moved to a new file in Interpolation directory
