### ISSUE TITLE
Add Distribution, Connector PContainer classes

### ISSUE THREAD

**Issue by matt-frey** [IPPL-framework/ippl#186]
In GitLab by @aaadelmann on Jul 18, 2023, 13:17

Create the classes shown in
[ippl-v2.0.pdf](https://my-gitlab-bucket.s3.amazonaws.com/680486291/e5c2545ff4e6a7c7335958a7c8e206d0d203032e23912d1a89a276e8e3b45e22/ippl-v2.0.pdf)

Modify Alpine and then use the classes. This is a blue print for OPAL-X

**Comment by srikrrish** [comment]
Done in release 3.2.0
