### ISSUE TITLE
Warmup method in FFT class

### ISSUE THREAD

**Issue by s-mayani** [IPPL-framework/ippl#234]
It would be useful to have a method `warmup(Field& f)` in the FFT classes so that one can call it after initialising an FFT object in IPPL to warmup both forward and backward transforms. 

N.B. This cannot be automatically done in the constructor since we need to apply "empty" transforms on a field (which has to be passed by the user of the FFT class).

**Comment by aaadelmann** [comment]
Naively I would have done the warmup in the constructor of the 
solver classes, there we know the fields?

**Comment by s-mayani** [comment]
> Naively I would have done the warmup in the constructor of the solver classes, there we know the fields?

Yes, this is how it's done currently. I thought it would be good to just be able to call `fft_m->warmup(field);` instead of:
`fft_m->transform(FORWARD, field); 
fft_m->transform(BACKWARD, field);`
every time we want to warm up an FFT object.

**Comment by aaadelmann** [comment]
ok now I see your point and agree!
