### ISSUE TITLE
Extra Printing 

### ISSUE THREAD

**Issue by mohsensadr** [IPPL-framework/ippl#243]
@s-mayani  @vmontanaro  Is this line necessary or was it left out from debugging?

https://github.com/IPPL-framework/ippl/blob/b23b7afc1c976056da369029192e39d6e570a31b/src/Particle/ParticleSpatialLayout.hpp#L296

**Comment by aaadelmann** [comment]
This can be deleted. We should (except for debugging) never use std::cout always Inform

**Comment by srikrrish** [comment]
This has been removed in release 3.2.0
