### ISSUE TITLE
locateParticles not working properly

### ISSUE THREAD

**Issue by manuel5975p** [IPPL-framework/ippl#254]
Currently, the master and dev branches have two different implementations of the `locateParticles` function:

[master](https://github.com/IPPL-framework/ippl/blob/master/src/Particle/ParticleSpatialLayout.hpp#L167-L194)

[dev-3.2.0](https://github.com/IPPL-framework/ippl/blob/dev-3.2.0/src/Particle/ParticleSpatialLayout.hpp#L206-L320)

There is one problem with the implementation on 
[master](https://github.com/IPPL-framework/ippl/blob/master/src/Particle/ParticleSpatialLayout.hpp#L167-L194): Particles that are on a boundary between two rank domains appear on both ranks. This is very, very rarely a problem, but it can definitely occur, especially when manually placing particles (e.g. at {0.5,0.5,0.5}).

Additionally the [dev-3.2.0](https://github.com/IPPL-framework/ippl/blob/dev-3.2.0/src/Particle/ParticleSpatialLayout.hpp#L206-L320) implementation doesn't seem to work for particles that need to be sent to non-adjacent ranks. I don't see completely through it though.

**Comment by matt-frey** [comment]
We reverted to the old method.
