### ISSUE TITLE
Utility/UserList.cpp and Utility/UserList.h cause compilation error on Apple Clang 

### ISSUE THREAD

**Issue by rammann** [IPPL-framework/ippl#259]
`Utility/UserList.h` includes the file `Utility/vmap.h` which makes use of a deprecated function `std::binary_function`. In case `UserList.h/UserList.cpp` aren't used anymore, the easiest fix would be to commend them from the `Utility/CMakeLists.txt` file.

**Comment by s-mayani** [comment]
This has been addressed in the PR by Manuel with has just been merged.
