### ISSUE TITLE
Sampling for a specific range

### ISSUE THREAD

**Issue by mohsensadr** [IPPL-framework/ippl#310]
@srikrrish 
Would it make sense to allow the user to specify the range of index in the for loop, instead of always 0-numlocal_m? I have to use subview to do this on the user side.

https://github.com/IPPL-framework/ippl/blob/fa287d096796f94099f0229a489f253d60062f26/src/Random/InverseTransformSampling.h#L246C9-L256C10

**Comment by srikrrish** [comment]
What do you mean range of index? Do you want to select a subset of generated random numbers?

**Comment by mohsensadr** [comment]
I mean, generating samples for a subset of the view.

Instead of 
`Kokkos::parallel_for(numlocal_m, fill_random<Kokkos::Random_XorShift64_Pool<>>(targetdist_m, view, rand_pool64, minbound_m, maxbound_m, d));`

where it loops over 0-numlocal_m and generates samples for view[0 : numlocal_m], I suggest something like

`Kokkos::parallel_for(Kokkos::RangePolicy<>(startIndex,endIndex), fill_random<Kokkos::Random_XorShift64_Pool<>>(targetdist_m, view, rand_pool64, minbound_m, maxbound_m, d));`

which generates the samples for view[startIndex : endIndex].

**Comment by srikrrish** [comment]
To me this can be done outside as this seems somewhat specific to your use case. Or where do you need this?

**Comment by mohsensadr** [comment]
I need this for sampling time in flat top distribution. I need to sample tail of a Gaussian for [0:numFall], sample uniform distribution for [numFall:numFall+numFlat] and sample tail of another Gaussian for [numFall + numFlat : ntotal].

**Comment by srikrrish** [comment]
I see.. I guess we can add that. @matt-frey what do you think?

**Comment by srikrrish** [comment]
Hi @mohsensadr we discussed this during our meeting today with Andreas and Matthias and yes we can have this feature. So please go ahead with it.

**Comment by mohsensadr** [comment]
Ok, thanks.
